In [1]:
l = list() #empty list
print (l)

[]


In [2]:
l = [1,2,3,4] #list of integers
print (l)

[1, 2, 3, 4]


In [3]:
l = [1,2,3, 4.5, 5.1] #list of numbers
print (l)

[1, 2, 3, 4.5, 5.1]


In [4]:
l = ["a","b",'c'] #list of characters
print (l)

['a', 'b', 'c']


In [5]:
l = [1,2,4.5,'abs',True] #mixed list
print (l)

[1, 2, 4.5, 'abs', True]


In [6]:
l = ["abc","pqr","xyz"] #list of strings
print (l)

['abc', 'pqr', 'xyz']


In [7]:
l=list('hello')
print(l)

['h', 'e', 'l', 'l', 'o']


In [8]:
s=('a','b','c','d','e')
l=list(s)
print(l)

['a', 'b', 'c', 'd', 'e']


In [9]:
l=list(input("Enter a list"))
print(l)

Enter a list Have a nice day


['H', 'a', 'v', 'e', ' ', 'a', ' ', 'n', 'i', 'c', 'e', ' ', 'd', 'a', 'y']


In [10]:
l=[1,[2,3],[4,5],[6,7,8],['Divya','Anu','Suchi']] #Nested List
print(l)

[1, [2, 3], [4, 5], [6, 7, 8], ['Divya', 'Anu', 'Suchi']]


In [11]:
len(l) #length of a list

5

In [12]:
l[3]  #indexing

[6, 7, 8]

In [13]:
l[2:4] #slicing

[[4, 5], [6, 7, 8]]

In [14]:
[-1,2,3] > [1,2,0]

False

In [15]:
[1,2,3] < [8,9,1]

True

In [22]:
l1=[1,2]
l2=[5,4,3]
l = l1+l2
print(l)

[1, 2, 5, 4, 3]


In [18]:
print(l*10) #Replicating a list

[1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3]


In [19]:
l=l*5
seq = l[2:15:3] #L[start:end:step]
print(seq)

[5, 1, 4, 2, 3]


In [23]:
print(l)
l=l*4
print(l)
print(l[::3]) #print the elements from initial index to last index with increment of 3 index.

[1, 2, 5, 4, 3]
[1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3]
[1, 4, 2, 3, 5, 1, 4]


In [24]:
l1=[1,2]
l2=[5,4,3]
l = l1+l2
l=l*3
print(l)
l[0:2] = ['one','two']
print(l)

[1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3]
['one', 'two', 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3]


In [25]:
l.append('new item') #add an element
print(l)

['one', 'two', 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [26]:
l[3] = 'updated item' #replace an element
print(l)

['one', 'two', 5, 'updated item', 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [27]:
del l[3]  #delete an item
print(l)

['one', 'two', 5, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [28]:
del l[1]  #delete an item
print(l)

['one', 5, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [29]:
l[5] = "item 1"
l[6] = "item2"
print(l)

['one', 5, 3, 1, 2, 'item 1', 'item2', 3, 1, 2, 5, 4, 3, 'new item']


In [30]:
del l[5:7]  #delete a slice
print(l)

['one', 5, 3, 1, 2, 3, 1, 2, 5, 4, 3, 'new item']


In [31]:
l.pop() #remove last element of the list
print(l)

['one', 5, 3, 1, 2, 3, 1, 2, 5, 4, 3]


In [32]:
l.pop(2) #removes an element at a position
print(l)

['one', 5, 1, 2, 3, 1, 2, 5, 4, 3]


In [40]:
l.index(2) #prints the index at which 2 is present

3

In [41]:
t=['a','b','Banasthali',1,2,3]
l.extend(t)
print(l)

['one', 5, 1, 2, 3, 1, 2, 5, 4, 3, 'a', 'b', 'Banasthali', 1, 2, 3]


In [42]:
l.insert(4,"Hello")
print(l)

['one', 5, 1, 2, 'Hello', 3, 1, 2, 5, 4, 3, 'a', 'b', 'Banasthali', 1, 2, 3]


In [43]:
if 1 not in l:
    print("Element not found")
else:
    l.remove(1)
    print("Element Deleted")
print(l)

Element Deleted
['one', 5, 2, 'Hello', 3, 1, 2, 5, 4, 3, 'a', 'b', 'Banasthali', 1, 2, 3]


In [44]:
l.append(4)
l.count(4) #number of times 4 is present in the list

2

In [45]:
print(l)
l.reverse()
print(l)

['one', 5, 2, 'Hello', 3, 1, 2, 5, 4, 3, 'a', 'b', 'Banasthali', 1, 2, 3, 4]
[4, 3, 2, 1, 'Banasthali', 'b', 'a', 3, 4, 5, 2, 1, 3, 'Hello', 2, 5, 'one']


In [54]:
l1=['e','i','q','a','q','p','b']
l2=l1
l1.sort()
print(l1)
print(l2)
#print(sorted(l2))

['a', 'b', 'e', 'i', 'p', 'q', 'q']
['a', 'b', 'e', 'i', 'p', 'q', 'q']


In [55]:
l.clear()
print(l)

[]


# Creating a Matrix

In [60]:
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
  
# Initialize matrix 
matrix = [] 
print("Enter the entries rowwise:") 
  
# For user input 
for i in range(R):          # A for loop for row entries 
    a =[] 
    for j in range(C):      # A for loop for column entries 
         a.append(int(input())) 
    matrix.append(a) 
  
# For printing the matrix 
for i in range(R): 
    for j in range(C): 
        print(matrix[i][j], end = " ") 
    print() 

Enter the number of rows: 3
Enter the number of columns: 2


Enter the entries rowwise:


 2
 3
 4
 5
 6
 7


2 3 
4 5 
6 7 


# Lab 4
1. WAP to find minimum element from a list of integers alongwith its index in the list
2. WAP to calcualte mean of a given list of numbers
3. WAP to search an element in a list
4. WAP to count the frequency of an element in a list
5. WAP to find frequencies of all elements in a list
6. WAP to extact two slices from a list and add the slices and find which one is greater
7. WAP to find second largest number of a list
8. WAP to input a list of numbers and shift all zeros to the right and all non zeros to left of the list
9. WAP to add two matrices
10. WAP to multiply two matrices
11. WAP to print transpose of a matrix
12. WAP to add elements of diagonal of a matrix
13. WAP to find an element in a matrix
14. WAP to find inverse of a matrix

In [61]:
l=[15,6,9,1,0,8]
min=1000
for i in l:
    if i < min:
        min=i
idx=l.index(min)
print("Minimum Element is {}".format(min) , end = "\t")
print("Index is {}".format(idx))

Minimum Element is 0	Index is 4


In [65]:
# 1. WAP to find minimum element from a list of integers alongwith its index in the list
l = [] 
n = int(input("Enter number of elements : ")) 
for i in range(0, n): 
    ele = int(input()) 
    l.append(ele) 
min = l[0]
for i in l:
    if i < min:
        min = i
index = l.index(min)
print("Minimum element of the given list is ",min," and it is present on index ",index)
        

Enter number of elements :  7
 4
 0
 9
 2
 6
 1
 7


Minimum element of the given list is  0  and it is present on index  1


In [79]:
# 2. WAP to calcualte mean of a given list of numbers
l = [3,5,9,2,1,8] 
s = 0
for i in range(len(l)): 
    s = s + l[i] 
s = s / len(l)
print("Mean of the given list is ",s)

Mean of the given list is  4.666666666666667


In [90]:
# 3. WAP to search an element in a list
num = int(input("Enter the element to search : "))
f = 0
for i in range(len(l)):
    if num == l[i]:
        print(num," is present at index ",i)
        f = 1
        break
if f == 0:        
    print(num," is not present in the list")

Enter the element to search :  8


8  is present at index  5


In [97]:
# 4. WAP to count the frequency of an element in a list
num = int(input("Enter the element whose frequency you want to count : "))
print(num, "is present ",l.count(num)," times")

Enter the element whose frequency you want to count :  3


3 is present  1  times


In [130]:
# 5. WAP to find frequencies of all elements in a list
if __name__ == "__main__":
    my_list =[1, 1, 1, 5, 5, 3, 1, 3, 3, 1, 4, 4, 4, 2, 2, 2, 2]
    freq = {} # Creating an empty dictionary
    for i in my_list:
        freq[i] = my_list.count(i)
     
    for key, value in freq.items():
        print ("% d : % d"%(key, value))

 1 :  5
 5 :  2
 3 :  3
 4 :  3
 2 :  4


In [133]:
# 6. WAP to extract two slices from a list and add the slices and find which one is greater
list1 = [10, 20, 4, 45, 99, 20, 99, 65]
slice1 = list1[2:5]
slice2 = list1[4:8]
print("Slice1 : ",slice1)
print("Slice2 : ",slice2)
add_slices = slice1 + slice2
print("Sum of slice1 and slice2 : ",add_slices)
if slice1 > slice2:
    print(slice1," is greater")
else:
    print(slice2," is greater")

Slice1 :  [4, 45, 99]
Slice2 :  [99, 20, 99, 65]
Sum of slice1 and slice2 :  [4, 45, 99, 99, 20, 99, 65]
[99, 20, 99, 65]  is greater


In [100]:
# 7. WAP to find second largest number of a list
list1 = [10, 20, 4, 45, 99, 20, 99, 65]
new_list = set(list1)
new_list.remove(max(new_list))
print(max(new_list))

65


In [129]:
# 8. WAP to input a list of numbers and shift all zeros to the right and all non zeros to left of the list

lst = []            
num = int(input("Enter the size of list : "))
for i in range(num):
    ele = int(input()) 
    lst.append(ele)
count = 0
for i in range(num):
    if lst[i] != 0:
        lst[count] = lst[i]
        count+=1
while count < num:
    lst[count] = 0
    count += 1
    
print("List after pushing all zeros to end of list:")
print(lst)

Enter the size of list :  6
 3
 0
 0
 8
 6
 5


List after pushing all zeros to end of list:
[3, 8, 6, 5, 0, 0]


In [102]:
# 9. WAP to add two matrices
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
  
Y = [[9,18,7],
    [6,5,4],
    [3,2,1]]
 
result = [[X[i][j] + Y[i][j]  for j in range(len(X[0]))] for i in range(len(X))]
  
for r in result:
    print(r)

[10, 20, 10]
[10, 10, 10]
[10, 10, 10]


In [105]:
# 10. WAP to multiply two matrices
#import numpy as np
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
   
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]

result= [[0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
            
#result = np.dot(A,B)
for r in result:
    print(r)
 

 

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [106]:
# 11. WAP to print transpose of a matrix
import numpy 
print(A)
print("\n")
print(numpy.transpose(A))

[[12, 7, 3], [4, 5, 6], [7, 8, 9]]


[[12  4  7]
 [ 7  5  8]
 [ 3  6  9]]


In [124]:
# 12. WAP to add elements of diagonal of a matrix

mat = [[ 1, 2, 3, 9 ],
     [ 5, 6, 7, 8 ],
     [ 1, 2, 3, 4 ],
     [ 5, 6, 7, 8 ]]

principal = 0
secondary = 0

for i in range(len(mat)):
    principal += mat[i][i]
    secondary += mat[i][len(mat) - i - 1]
         
print("Principal Diagonal:", principal)
print("Secondary Diagonal:", secondary)

Principal Diagonal: 18
Secondary Diagonal: 23


In [121]:
# 13. WAP to find an element in a matrix

test_list = [[4, 5, 6],
             [10, 2, 13],
             [1, 11, 18]]
  
print("The original list : " + str(test_list))
  
num = int(input("Enter the element you want to search : "))    
res = any(num in sub for sub in test_list)
if res == True:
    print(num," is present in matrix")
else:
    print(num," is not present in matrix")

The original list : [[4, 5, 6], [10, 2, 13], [1, 11, 18]]


Enter the element you want to search :  11


11  is present in matrix


In [113]:
# 14. WAP to find inverse of a matrix
import numpy as np
A = np.array([[[1, 2], [3, 4]],
              [[1, 3], [3, 5]]])
              
print("Original Matrix\n") 
print(A,"\n")
print("Inverse Matrix\n")
print(np.linalg.inv(A))

Original Matrix

[[[1 2]
  [3 4]]

 [[1 3]
  [3 5]]] 

Inverse Matrix

[[[-2.    1.  ]
  [ 1.5  -0.5 ]]

 [[-1.25  0.75]
  [ 0.75 -0.25]]]
